# Generated by Django 4.1.5 on 2023-01-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
   
        migrations.CreateModel(
            name='InfosSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nombre_invite', models.PositiveIntegerField()),
                ('machine_a_cafe', models.BooleanField()),
                ('tableau_blanc', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('projecteur', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SalleReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_evt', models.DateField()),
            ],
        ),
    ]
