# Generated by Django 4.1.5 on 2023-01-06 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_infossalle_nombre_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='infossalle',
            name='date_de_reservation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='infossalle',
            name='en_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infossalle',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
    ]
