# Generated by Django 4.1.5 on 2023-01-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_infossalle_date_de_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infossalle',
            name='date_de_reservation',
            field=models.DateField(default='0001-01-01'),
        ),
    ]
