# Generated by Django 4.1.5 on 2023-01-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_infossalle_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infossalle',
            name='date_de_reservation',
        ),
    ]
